apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-api-staging
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: financial-api
      env: staging
  template:
    metadata:
      labels:
        app: financial-api
        env: staging
    spec:
      containers:
      - name: financial-api
        image: your-registry/financial-api:staging
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "staging"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: host
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 