apiVersion: v1
kind: Service
metadata:
  name: financial-api-staging
  namespace: staging
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: financial-api
    env: staging 